columns:
  "Unnamed: 0": "int64"
  "PROSPECTID": "int64"
  "Total_TL": "int64"
  "Tot_Closed_TL": "int64"
  "Tot_Active_TL": "int64"
  "Total_TL_opened_L6M": "int64"
  "Tot_TL_closed_L6M": "int64"
  "pct_tl_open_L6M": "float64"
  "pct_tl_closed_L6M": "float64"
  "pct_active_tl": "float64"
  "pct_closed_tl": "float64"
  "Total_TL_opened_L12M": "int64"
  "Tot_TL_closed_L12M": "int64"
  "pct_tl_open_L12M": "float64"
  "pct_tl_closed_L12M": "float64"
  "Tot_Missed_Pmnt": "int64"
  "Auto_TL": "int64"
  "CC_TL": "int64"
  "Consumer_TL": "int64"
  "Gold_TL": "int64"
  "Home_TL": "int64"
  "PL_TL": "int64"
  "Secured_TL": "int64"
  "Unsecured_TL": "int64"
  "Other_TL": "int64"
  "Age_Oldest_TL": "int64"
  "Age_Newest_TL": "int64"
  "time_since_recent_payment": "int64"
  "time_since_first_deliquency": "int64"
  "time_since_recent_deliquency": "int64"
  "num_times_delinquent": "int64"
  "max_delinquency_level": "int64"
  "max_recent_level_of_deliq": "int64"
  "num_deliq_6mts": "int64"
  "num_deliq_12mts": "int64"
  "num_deliq_6_12mts": "int64"
  "max_deliq_6mts": "int64"
  "max_deliq_12mts": "int64"
  "num_times_30p_dpd": "int64"
  "num_times_60p_dpd": "int64"
  "num_std": "int64"
  "num_std_6mts": "int64"
  "num_std_12mts": "int64"
  "num_sub": "int64"
  "num_sub_6mts": "int64"
  "num_sub_12mts": "int64"
  "num_dbt": "int64"
  "num_dbt_6mts": "int64"
  "num_dbt_12mts": "int64"
  "num_lss": "int64"
  "num_lss_6mts": "int64"
  "num_lss_12mts": "int64"
  "recent_level_of_deliq": "int64"
  "tot_enq": "int64"
  "CC_enq": "int64"
  "CC_enq_L6m": "int64"
  "CC_enq_L12m": "int64"
  "PL_enq": "int64"
  "PL_enq_L6m": "int64"
  "PL_enq_L12m": "int64"
  "time_since_recent_enq": "int64"
  "enq_L12m": "int64"
  "enq_L6m": "int64"
  "enq_L3m": "int64"
  "MARITALSTATUS": "object"
  "EDUCATION": "object"
  "AGE": "int64"
  "GENDER": "object"
  "NETMONTHLYINCOME": "int64"
  "Time_With_Curr_Empr": "int64"
  "pct_of_active_TLs_ever": "float64"
  "pct_opened_TLs_L6m_of_L12m": "float64"
  "pct_currentBal_all_TL": "float64"
  "CC_utilization": "float64"
  "CC_Flag": "int64"
  "PL_utilization": "float64"
  "PL_Flag": "int64"
  "pct_PL_enq_L6m_of_L12m": "float64"
  "pct_CC_enq_L6m_of_L12m": "float64"
  "pct_PL_enq_L6m_of_ever": "float64"
  "pct_CC_enq_L6m_of_ever": "float64"
  "max_unsec_exposure_inPct": "float64"
  "HL_Flag": "int64"
  "GL_Flag": "int64"
  "last_prod_enq2": "object"
  "first_prod_enq2": "object"
  "Credit_Score": "int64"
  "Approved_Flag": "object"

target_column: "Approved_Flag"

strict: true

